
networks:
  backend:
    external: true

services:
  helldivers2armorer:
    image: registry.gitlab.lan:5050/jhr/helldivers2armorer:latest
    pull_policy: always
    restart: unless-stopped
    stdin_open: true
    tty: true
    # ports:
    #   - 8080:80/tcp
    networks:
      - backend
    labels:
      - traefik.enable=true
      - traefik.docker.network=backend
      - traefik.http.routers.hd2armorer.tls=true
      - traefik.http.routers.hd2armorer.rule=Host(`hd2armorer.lan`)
      - traefik.http.routers.hd2armorer.service=hd2armorer_svc
      - traefik.http.services.hd2armorer_svc.loadbalancer.server.port=80
      - traefik.http.services.hd2armorer_svc.loadbalancer.server.scheme=http
